version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: unless-stopped
    networks:
      app:
    ports:
      - "8080:8080"


networks:
  app:
    driver: bridge